"""empty message

Revision ID: 2da1d8dd61c7
Revises: 
Create Date: 2024-01-25 22:22:25.096466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da1d8dd61c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artikel',
    sa.Column('idartikel', sa.Integer(), nullable=False),
    sa.Column('judulartikel', sa.String(length=150), nullable=True),
    sa.Column('detailartikel', sa.String(length=1000), nullable=True),
    sa.Column('namaaenulis', sa.String(length=100), nullable=True),
    sa.Column('tanggalterbit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idartikel'),
    sa.UniqueConstraint('judulartikel')
    )
    op.create_table('bahanmakanan',
    sa.Column('id_bahan', sa.Integer(), nullable=False),
    sa.Column('namabahan', sa.String(length=100), nullable=True),
    sa.Column('deskripsibahan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_bahan')
    )
    op.create_table('detailnutrisi',
    sa.Column('id_detailnutrisi', sa.Integer(), nullable=False),
    sa.Column('jumlahnutrisi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_detailnutrisi')
    )
    op.create_table('nutrisi',
    sa.Column('id_nutrisi', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_nutrisi'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('tanggallahir', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('resepmakanan',
    sa.Column('id_resep', sa.Integer(), nullable=False),
    sa.Column('id_detailnutrisi', sa.Integer(), nullable=True),
    sa.Column('namamakanan', sa.String(length=100), nullable=True),
    sa.Column('langkahpembuatan', sa.String(length=200), nullable=True),
    sa.Column('jumlahporsi', sa.Integer(), nullable=True),
    sa.Column('waktumemasak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_detailnutrisi'], ['detailnutrisi.id_detailnutrisi'], ),
    sa.PrimaryKeyConstraint('id_resep'),
    sa.UniqueConstraint('namamakanan')
    )
    op.create_table('resepmakanandetail',
    sa.Column('id_resepdetail', sa.Integer(), nullable=False),
    sa.Column('id_resep', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('jumlahbahan', sa.Float(), nullable=True),
    sa.Column('satuanjumlah', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bahanmakanan.id_bahan'], ),
    sa.ForeignKeyConstraint(['id_resep'], ['resepmakanan.id_resep'], ),
    sa.PrimaryKeyConstraint('id_resepdetail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resepmakanandetail')
    op.drop_table('resepmakanan')
    op.drop_table('user')
    op.drop_table('nutrisi')
    op.drop_table('detailnutrisi')
    op.drop_table('bahanmakanan')
    op.drop_table('artikel')
    # ### end Alembic commands ###
