"""empty message

Revision ID: 427e4979ca0a
Revises: 67d3426a686b
Create Date: 2024-02-01 15:15:26.408826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '427e4979ca0a'
down_revision = '67d3426a686b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bahanmakanan')
    op.drop_table('detailnutrisi')
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.drop_index('judulartikel')

    op.drop_table('artikel')
    with op.batch_alter_table('nutrisi', schema=None) as batch_op:
        batch_op.drop_index('nama')

    op.drop_table('nutrisi')
    with op.batch_alter_table('resepmakanan', schema=None) as batch_op:
        batch_op.drop_index('namamakanan')

    op.drop_table('resepmakanan')
    op.drop_table('resepmakanandetail')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('tanggallahir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggallahir', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('birth')

    op.create_table('resepmakanandetail',
    sa.Column('id_resepdetail', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_resep', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('jumlahbahan', mysql.FLOAT(), nullable=True),
    sa.Column('satuanjumlah', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bahanmakanan.id_bahan'], name='resepmakanandetail_ibfk_1'),
    sa.ForeignKeyConstraint(['id_resep'], ['resepmakanan.id_resep'], name='resepmakanandetail_ibfk_2'),
    sa.PrimaryKeyConstraint('id_resepdetail'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resepmakanan',
    sa.Column('id_resep', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_detailnutrisi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('namamakanan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('langkahpembuatan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('jumlahporsi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('waktumemasak', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_detailnutrisi'], ['detailnutrisi.id_detailnutrisi'], name='resepmakanan_ibfk_1'),
    sa.PrimaryKeyConstraint('id_resep'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resepmakanan', schema=None) as batch_op:
        batch_op.create_index('namamakanan', ['namamakanan'], unique=True)

    op.create_table('nutrisi',
    sa.Column('id_nutrisi', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_nutrisi'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nutrisi', schema=None) as batch_op:
        batch_op.create_index('nama', ['nama'], unique=True)

    op.create_table('artikel',
    sa.Column('idartikel', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('judulartikel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('detailartikel', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('namaaenulis', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tanggalterbit', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idartikel'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.create_index('judulartikel', ['judulartikel'], unique=True)

    op.create_table('detailnutrisi',
    sa.Column('id_detailnutrisi', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('jumlahnutrisi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_detailnutrisi'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bahanmakanan',
    sa.Column('id_bahan', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('namabahan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('deskripsibahan', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_bahan'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
