"""empty message

Revision ID: 5010b17e0941
Revises: b7bda6cda028
Create Date: 2024-01-25 22:11:31.350512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5010b17e0941'
down_revision = 'b7bda6cda028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artikel',
    sa.Column('idartikel', sa.Integer(), nullable=False),
    sa.Column('judulartikel', sa.String(length=150), nullable=True),
    sa.Column('detailartikel', sa.String(length=1000), nullable=True),
    sa.Column('namaaenulis', sa.String(length=100), nullable=True),
    sa.Column('tanggalterbit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idartikel'),
    sa.UniqueConstraint('judulartikel')
    )
    op.create_table('bahanmakanan',
    sa.Column('id_bahan', sa.Integer(), nullable=False),
    sa.Column('namabahan', sa.String(length=100), nullable=True),
    sa.Column('deskripsibahan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_bahan')
    )
    op.create_table('detailnutrisi',
    sa.Column('id_detailnutrisi', sa.Integer(), nullable=False),
    sa.Column('jumlahnutrisi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_detailnutrisi')
    )
    op.create_table('nutrisi',
    sa.Column('id_nutrisi', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_nutrisi'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('resepmakanan',
    sa.Column('id_resep', sa.Integer(), nullable=False),
    sa.Column('id_detailnutrisi', sa.Integer(), nullable=True),
    sa.Column('namamakanan', sa.String(length=100), nullable=True),
    sa.Column('langkahpembuatan', sa.String(length=200), nullable=True),
    sa.Column('jumlahporsi', sa.Integer(), nullable=True),
    sa.Column('waktumemasak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_detailnutrisi'], ['detailnutrisi.id_detailnutrisi'], ),
    sa.PrimaryKeyConstraint('id_resep'),
    sa.UniqueConstraint('namamakanan')
    )
    op.create_table('resepmakanandetail',
    sa.Column('id_resepdetail', sa.Integer(), nullable=False),
    sa.Column('id_resep', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('jumlahbahan', sa.Float(), nullable=True),
    sa.Column('satuanjumlah', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bahanmakanan.id_bahan'], ),
    sa.ForeignKeyConstraint(['id_resep'], ['resepmakanan.id_resep'], ),
    sa.PrimaryKeyConstraint('id_resepdetail')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tanggallahir', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tanggallahir')
        batch_op.drop_column('username')

    op.drop_table('resepmakanandetail')
    op.drop_table('resepmakanan')
    op.drop_table('nutrisi')
    op.drop_table('detailnutrisi')
    op.drop_table('bahanmakanan')
    op.drop_table('artikel')
    # ### end Alembic commands ###
