"""empty message

Revision ID: 67d3426a686b
Revises: 5010b17e0941
Create Date: 2024-02-01 15:14:55.211281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d3426a686b'
down_revision = '5010b17e0941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutritiondetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutritionamount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.String(length=200), nullable=True),
    sa.Column('portions', sa.Integer(), nullable=True),
    sa.Column('cooktime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('publishdate', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('favoriterecipe',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('nutritions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutritiondetail_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nutritiondetail_id'], ['nutritiondetails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrition_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['nutrition_id'], ['nutritions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipedetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredients_id', sa.Integer(), nullable=True),
    sa.Column('ingredientamount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bahanmakanan')
    with op.batch_alter_table('resepmakanan', schema=None) as batch_op:
        batch_op.drop_index('namamakanan')

    op.drop_table('resepmakanan')
    with op.batch_alter_table('nutrisi', schema=None) as batch_op:
        batch_op.drop_index('nama')

    op.drop_table('nutrisi')
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.drop_index('judulartikel')

    op.drop_table('artikel')
    op.drop_table('resepmakanandetail')
    op.drop_table('detailnutrisi')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('tanggallahir')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggallahir', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('birth')

    op.create_table('detailnutrisi',
    sa.Column('id_detailnutrisi', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('jumlahnutrisi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_detailnutrisi'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resepmakanandetail',
    sa.Column('id_resepdetail', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_resep', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('jumlahbahan', mysql.FLOAT(), nullable=True),
    sa.Column('satuanjumlah', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['bahanmakanan.id_bahan'], name='resepmakanandetail_ibfk_1'),
    sa.ForeignKeyConstraint(['id_resep'], ['resepmakanan.id_resep'], name='resepmakanandetail_ibfk_2'),
    sa.PrimaryKeyConstraint('id_resepdetail'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('artikel',
    sa.Column('idartikel', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('judulartikel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('detailartikel', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('namaaenulis', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('tanggalterbit', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('idartikel'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.create_index('judulartikel', ['judulartikel'], unique=True)

    op.create_table('nutrisi',
    sa.Column('id_nutrisi', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_nutrisi'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nutrisi', schema=None) as batch_op:
        batch_op.create_index('nama', ['nama'], unique=True)

    op.create_table('resepmakanan',
    sa.Column('id_resep', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_detailnutrisi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('namamakanan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('langkahpembuatan', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('jumlahporsi', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('waktumemasak', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_detailnutrisi'], ['detailnutrisi.id_detailnutrisi'], name='resepmakanan_ibfk_1'),
    sa.PrimaryKeyConstraint('id_resep'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resepmakanan', schema=None) as batch_op:
        batch_op.create_index('namamakanan', ['namamakanan'], unique=True)

    op.create_table('bahanmakanan',
    sa.Column('id_bahan', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('namabahan', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('deskripsibahan', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_bahan'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recipedetails')
    op.drop_table('ingredients')
    op.drop_table('nutritions')
    op.drop_table('favoriterecipe')
    op.drop_table('article')
    op.drop_table('recipes')
    op.drop_table('nutritiondetails')
    # ### end Alembic commands ###
