"""empty message

Revision ID: 780c5ec31bda
Revises: 5ca72e493000
Create Date: 2024-02-01 14:52:50.794858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780c5ec31bda'
down_revision = '5ca72e493000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutritions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutritiondetail_id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nutritiondetail_id'], ['nutritiondetails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutritions')
    # ### end Alembic commands ###
