"""empty message

Revision ID: 819c3d7eeedf
Revises: 780c5ec31bda
Create Date: 2024-02-01 14:53:13.244526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819c3d7eeedf'
down_revision = '780c5ec31bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrition_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['nutrition_id'], ['nutritions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    # ### end Alembic commands ###
