"""empty message

Revision ID: 869a6fea5873
Revises: e12cf1072adb
Create Date: 2024-02-01 14:54:39.320817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869a6fea5873'
down_revision = 'e12cf1072adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.String(length=200), nullable=True),
    sa.Column('portions', sa.Integer(), nullable=True),
    sa.Column('cooktime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
