"""empty message

Revision ID: 937e8ef647d6
Revises: 861dd4b63f64
Create Date: 2024-02-20 14:55:15.040200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '937e8ef647d6'
down_revision = '861dd4b63f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutritiondetails', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('nutritions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=200), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutritions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('unit')

    with op.batch_alter_table('nutritiondetails', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
