"""empty message

Revision ID: 970d55b5e7e2
Revises: 3694514901ef
Create Date: 2024-02-01 14:55:07.613902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970d55b5e7e2'
down_revision = '3694514901ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipedetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredients_id', sa.Integer(), nullable=True),
    sa.Column('ingredientamount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipedetails')
    # ### end Alembic commands ###
