"""empty message

Revision ID: ac924f696e4c
Revises: f1dacc7cc6b9
Create Date: 2024-02-19 18:11:54.260841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac924f696e4c'
down_revision = 'f1dacc7cc6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipedetails', schema=None) as batch_op:
        batch_op.drop_constraint('recipedetails_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ingredients', ['ingredients_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipedetails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipedetails_ibfk_1', 'ingredients', ['ingredients_id'], ['id'])

    # ### end Alembic commands ###
