"""empty message

Revision ID: ded503cb1a98
Revises: fe060169eb86
Create Date: 2024-02-15 16:25:50.362963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ded503cb1a98'
down_revision = 'fe060169eb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('recipedetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.drop_column('ingredientamount')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('favorite_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('portion', sa.Float(), nullable=True))
        batch_op.alter_column('steps',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_column('portions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.alter_column('steps',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('portion')
        batch_op.drop_column('favorite_count')
        batch_op.drop_column('image')

    with op.batch_alter_table('recipedetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredientamount', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('amount')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
