"""empty message

Revision ID: f1dacc7cc6b9
Revises: 03d3453e1a8b
Create Date: 2024-02-19 18:08:48.947289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dacc7cc6b9'
down_revision = '03d3453e1a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipedetails', schema=None) as batch_op:
        batch_op.drop_constraint('recipedetails_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipedetails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipedetails_ibfk_2', 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
